version: "3.7"

services:
  eturnal:
    image: ghcr.io/processone/eturnal:latest
    hostname: eturnal
    container_name: eturnal
    restart: unless-stopped
    user: 9000:9000
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    # network_mode: "host"
    ports:
      - 3478:3478 # STUN/TURN non-tls
      - 3478:3478/udp # STUN/TURN non-tls
      # - 5349:5349 # STUN/TURN TLS
      # - 49152-65535:49152-65535/udp # TURN range
    # env_file:
    #   - eturnal.env
    # volumes: # directories must be owned by eturnal user 9000:9000
    #   - /path/to/eturnal.yml:/etc/eturnal.yml:ro # for custom config file
    #   - /path/to/tls-files:/opt/eturnal/tls      # for custom tls files
