name: Windows

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  installer:
    name: Build Windows installer
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with: # For scripts/get-version:
          fetch-depth: 0
      - name: Cache Rebar data
        uses: actions/cache@v3
        with:
          path: ~/.cache/rebar3
          key: ${{ runner.os }}-${{ hashFiles('rebar.config') }}
      - name: Download Erlang/OTP and Rebar
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.x'
          rebar3-version: '3.x'
      - name: Compile installer
        run: windows/make-installer
        shell: bash
      - name: Analyze cross references
        run: rebar3 xref
      - name: Perform static code analysis
        run: rebar3 dialyzer
      - name: Run black-box tests (CT)
        run: rebar3 ct
      - name: Run white-box tests (EUnit)
        run: rebar3 eunit
      - name: Check test coverage
        run: rebar3 cover
      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: eturnal-installer
          path: eturnal-*.exe
